project:
  type: website

website:
  title: "RSE survey analysis"
  navbar:
    left:
      - href: index.qmd
        text: "About"
      - href: disciplines.qmd
        text: "Disciplines"
      - href: testing.qmd
        text: "Testing practices"
      - href: version.qmd
        text: "Version control practices"
      - href: funding.qmd
        text: "Funding sources"
      - href: career_choice.qmd
        text: "Career choice"

    right:
      - icon: github
        href: https://github.com/SaranjeetKaur/RSE_historical_analysis

format: html
