---
title: "What have we learnt from the RSE journey so far"
author: "Saranjeet Kaur Bhogal"
date: "2026-03-29"
format: html
---

![The Turing Way project illustration by Scriberia. Used under a CC-BY 4.0 licence.
DOI: [The Turing Way Community & Scriberia
(2024)](https://doi.org/10.5281/ZENODO.3332807).](fig/research_environment.jpg)

The role of a Research Software Engineer (RSE) has been evolving since [the term was first
coined](https://www.software.ac.uk/about/research-software-engineers) at Software Sustainability
Institute's Collaborations Workshop 2012, almost a decade and a half ago. RSEs play an important
role in the research ecosystem by developing and maintaining software that supports research
activities.

The [international RSE survey](https://www.software.ac.uk/news/2026-international-rse-survey) is
an annual survey that collects data on the demographics, skills, practices, and
experiences of RSEs around the world. The survey has been conducted since 2016 providing an opportunity
to track the evolution of the RSE role over time. This is an analysis report based on the [RSE survey
data](https://github.com/softwaresaved/RSE_survey_longitudinal/) from 2016-2022. Data for the years 2019-2021
are not reported.

In this report, we explore the following aspects of the RSE community:

- [Disciplines in which RSEs work](disciplines.qmd)
- [How are RSEs typically testing software](testing.qmd)
- [Version control tools used for software development](version.qmd)
- [Funding sources for RSE work](funding.qmd)
- [Factors influencing the move to RSE roles](career_choice.qmd)